[versions]
kotlin = "2.2.0"
agp = "8.2.0"

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }

[libraries]
androidx-core-ktx = "androidx.core:core-ktx:1.12.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
androidx-activity-compose = "androidx.activity:activity-compose:1.8.2"
androidx-lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime-ktx:2.7.0"
compose-bom = "androidx.compose:compose-bom:2024.02.00"
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-material = { module = "androidx.compose.material:material" }
compose-runtime = { module = "androidx.compose.runtime:runtime" } 